import XLSX from 'xlsx';
import { parseRose, parseSvincolati } from '../public/xlsx-parse.js';
const B = 'http://localhost:8787', U = '/root/.claude/uploads/6071e3f5-f3e6-5fcc-ae06-ae77ef8892e2/';
const rose = parseRose(XLSX, XLSX.readFile(U + '1ffa4ff9-rose-308228-1.xlsx'));
const L = parseSvincolati(XLSX, XLSX.readFile(U + '70e4445d-quotazioni-valore.xlsx'));
const jar = {};
async function api(w, p, b) { const r = await fetch(B + p, { method: b ? 'POST' : 'GET', headers: { 'content-type': 'application/json', cookie: jar[w] || '' }, body: b ? JSON.stringify(b) : undefined }); const sc = r.headers.get('set-cookie'); if (sc) jar[w] = sc.split(';')[0]; const j = await r.json(); if (j.error) throw new Error(j.error); return j; }
const expectErr = async (p, l) => { try { await p; console.log('!! manca errore:', l); } catch (e) { console.log('  ok bloccato:', l, '→', e.message); } };
await api('admin', '/api/register', { email: 'silvello.enrico@gmail.com', name: 'Enrico', password: 'secret1' });
// listone before rose, then rose: both orders must work
console.log('listone:', await api('admin', '/api/admin', { type: 'import_listone', players: L }));
console.log('rose:', await api('admin', '/api/admin', { type: 'import_rose', teams: rose }));
let st = await api('admin', '/api/state');
const free = st.players.filter((p) => !p.team_id), ros = st.players.filter((p) => p.team_id);
console.log('svincolati', free.length, 'in rosa', ros.length, 'rosa senza quot', ros.filter((p) => p.quotazione == null).length, 'nessun doppione:', new Set(st.players.map((p) => p.name + p.club)).size === st.players.length);
console.log('ricarico listone:', await api('admin', '/api/admin', { type: 'import_listone', players: L }));
const T = (n) => st.teams.find((t) => t.name.includes(n)).id;
await api('admin', '/api/me/team', { team_id: T('Real Paese') });
let i = 0;
for (const t of st.teams) { if (t.name.includes('Real Paese')) continue; i++; await api('u' + t.id, '/api/register', { email: `u${i}@x.it`, name: 'Coach' + i, password: 'pwpwpw', team_id: t.id }); }
const who = (id) => (id === T('Real Paese') ? 'admin' : 'u' + id);
await api('admin', '/api/admin', { type: 'settings', settings: { default_cambi: '3', global_extra: '20', release_refund: 'min' }, apply_cambi_all: true });
await api('admin', '/api/admin', { type: 'start' });
st = await api('admin', '/api/state');
const t1 = +st.settings.turn_team_id; const tn = (id) => st.teams.find((t) => t.id === id).name;
const target = st.players.find((p) => !p.team_id && p.role === 'C' && p.quotazione >= 5);
await api(who(t1), '/api/action', { type: 'call', player_id: target.id, amount: 1 });
st = await api('admin', '/api/state');
for (const p of st.auction.participants) if (p.status === 'active' && p.team_id !== t1) await api(who(p.team_id), '/api/action', { type: 'withdraw' });
st = await api('admin', '/api/state');
console.log(target.name, '→', tn(st.auction.winner_team_id), '| turno a', tn(+st.settings.turn_team_id), '| svincolo dovuto', st.teams.find((t) => t.id === t1).pending_release);
const t2 = +st.settings.turn_team_id;
const other = st.players.find((p) => !p.team_id && p.role === 'D');
await expectErr(api(who(t2), '/api/action', { type: 'call', player_id: other.id }), 'asta prima dello svincolo');
const cands = st.players.filter((p) => p.team_id === t1 && p.role === 'C' && p.quotazione != null).sort((a, b) => (b.cost - b.quotazione) - (a.cost - a.quotazione));
const rel = cands[0]; const before = st.teams.find((t) => t.id === t1).credits;
await api(who(t1), '/api/action', { type: 'release', player_id: rel.id });
st = await api('admin', '/api/state');
console.log('svincolato', rel.name, 'costo', rel.cost, 'quot', rel.quotazione, '→ rimborso', st.teams.find((t) => t.id === t1).credits - before, '(atteso', Math.min(rel.cost, rel.quotazione) + ') | torna svincolato:', !st.players.find((p) => p.id === rel.id).team_id);
await api(who(t2), '/api/action', { type: 'call', player_id: other.id, amount: 1 });
console.log('dopo lo svincolo la nuova asta parte: OK');
