import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
await ctx.route(/fonts\.(googleapis|gstatic)/, r => r.abort());
const p = await ctx.newPage(); const errs=[]; p.on('pageerror', e => errs.push(e.message));
await p.goto('http://localhost:8787'); await p.fill('input[name=email]','silvello.enrico@gmail.com'); await p.fill('input[name=password]','secret1'); await p.click('button[type=submit]');
await p.waitForSelector('nav.tabs'); await p.waitForTimeout(4000);
await p.click('[data-tab=movimenti]'); await p.waitForTimeout(300);
await p.screenshot({ path: '/tmp/claude-0/shots/m1.png' });
await p.click('.li.click >> nth=0'); await p.waitForTimeout(300);
await p.screenshot({ path: '/tmp/claude-0/shots/m2.png' });
console.log('errori:', errs);
await b.close();
